### ISSUE TITLE
Error when executes auth.logout with the logoutEndpointUrl setted

### ISSUE THREAD

**Issue by siderlan** [willcrisis/angular-auth#2]
Hi,

I got the following error after executes the logout method from auth service:

Error: [$http:badreq] Http request configuration url must be a string or a $sce trusted object.  Received: undefined

The error was reported on the following statement:
`
if (authConf[service.endpoint].logoutEndpointUrl) {
return $http.get(authConf.logoutEndpointUrl);
 }
`

I guess that `return $http.get(authConf.logoutEndpointUrl);` should be replaced for `return $http.get(authConf[service.endpoint].logoutEndpointUrl);`

**Comment by siderlan** [comment]
I created a pull request to fix it: #3

**Comment by willcrisis** [comment]
Hello.

Sorry for the delay, and thanks for the PR. Already merged and a new version was released.

Thanks.
